<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CELSYSNCR000070" failures="4" tests="8" name="Surefire test" time="19.452" errors="0" timestamp="2023-12-29T16:39:47 IST">
  <testcase classname="api.test.DDTests" name="testPostuser" time="1.344">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void api.test.DDTests.testPostuser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testPostuser([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6])
Arguments: [(java.lang.String) 1010,(java.lang.String) testuser1,(java.lang.String) John]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void api.test.DDTests.testPostuser(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testPostuser([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6])
Arguments: [(java.lang.String) 1010,(java.lang.String) testuser1,(java.lang.String) John]
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testPostuser -->
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="3.337">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteUserByName(DDTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.682">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteUserByName(DDTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="2.036">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDTests.testDeleteUserByName(DDTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.UserTests" name="testPostUser" time="2.44"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="2.072"/>
  <testcase classname="api.test.UserTests" name="testUpdateUserByName" time="4.129"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="2.073"/>
</testsuite> <!-- Surefire test -->
